### PR TITLE
Fix redirect loop condition with edd redirect page

### LINKED ISSUE #12: Redirect loop case
If the Success Page in EDD is set to the same page as a custom redirect rule the customer is left in an endless redirect loop which at some point will error out.

@mintplugins tracked it down and i believe something like below on line 109 here should do the trick: 
https://github.com/easydigitaldownloads/edd-conditional-success-redirects/blob/master/includes/class-process-redirects.php#L109

````
$custom_redirect_url = $this->get_redirect();
$edd_success_page_url = get_permalink( edd_get_option( 'success_page' ) );

if ( $custom_redirect_url == $edd_success_page_url ) {
         return;
}
````

### PR DESCRIPTION
**Pull request by misulicus**
Fixes #12

### CODE REVIEW

File: includes/class-process-redirects.php [hunk 1]
```diff
@@ -107,6 +107,13 @@ public function process_offsite_payment() {
 				return;
 			}
 
+			$custom_redirect_url = $this->get_redirect();
+			$edd_success_page_url = get_permalink( edd_get_option( 'success_page' ) );
+
+			if ( $custom_redirect_url == $edd_success_page_url ) {
```
Comment (pippinsplugins) [inline includes/class-process-redirects.php]: Let's run these through `trailingslashit()` to help ensure we catch edge cases:
```php
if ( trailingslashit( $custom_redirect_url ) == trailingslashit( $edd_success_page_url ) ) {
```

Comment (misulicus) [reply includes/class-process-redirects.php]: change made below
